### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by keeper4** [whutD9LabWCG/CellIDAndLAC#1]
Ni has
What need to enter in TextField locationName??

**Comment by CodingGou** [comment]
the name of place you want  to store which contact with Cell ID

**Comment by CodingGou** [comment]
it works in iOS8.3 before,it store the name of the subwaystation which conetct with the CellID

**Comment by keeper4** [comment]
maybe I'm doing something wrong
log:       

 ttt =         {
            "CellID:" = "0.916308";
        };
    },
        {
        ttt =         {
            "CellID:" = "6.566524";
        };
    },
        {
        ttt =         {
            "CellID:" = "9.450500";
        };
    },
        {
        ttt =         {
            "CellID:" = "2.283390";
        };

**Comment by keeper4** [comment]
ttt its key

**Comment by CodingGou** [comment]
CellID must be a  int Number, may be you log  the time which  conect to the subwaystation ?
